//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public int ID { get; set; }
        public string REVIEW_CONTENT { get; set; }
        public Nullable<double> RATING { get; set; }
        public System.DateTime DAY { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> STORE_ID { get; set; }
    }
}
