//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVOURITE_LISTS
    {
        public int ID { get; set; }
        public string USER_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public string STORE_ID { get; set; }
    }
}
