//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int StoreId { get; set; }
    
        public virtual FavoriteList FavoriteList { get; set; }
        public virtual ProductImage ProductImage { get; set; }
        public virtual Store Store { get; set; }
        public virtual Review Review { get; set; }
    }
}
