//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> RATING { get; set; }
        public System.TimeSpan OPEN_HOUR { get; set; }
        public System.TimeSpan CLOSE_HOUR { get; set; }
        public Nullable<decimal> LOWEST_PRICE { get; set; }
        public Nullable<decimal> HIGHTEST_PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public int CATELOGY_ID { get; set; }
        public System.DateTime REGISTRATION_DAY { get; set; }
        public string ADDRESS { get; set; }
        public string DISTRICT { get; set; }
        public string CITY { get; set; }
    }
}
