//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;

    public partial class Comment
    {
        public System.Guid Id { get; set; }
        public string ReviewContent { get; set; }
        public Nullable<double> Rating { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }

        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
