//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    
        public virtual ProductImage ProductImage { get; set; }
        public virtual StoreImage StoreImage { get; set; }
        public virtual UserImage UserImage { get; set; }
    }
}
