//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Rating { get; set; }
        public System.TimeSpan OpenHour { get; set; }
        public System.TimeSpan CloseHour { get; set; }
        public Nullable<decimal> LowestPrice { get; set; }
        public Nullable<decimal> HighestPrice { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string City { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Comment Comment { get; set; }
        public virtual FavoriteList FavoriteList { get; set; }
        public virtual Product Product { get; set; }
        public virtual Review Review { get; set; }
        public virtual StoreImage StoreImage { get; set; }
    }
}
