//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Comments = new HashSet<Comment>();
            this.FavoriteLists = new HashSet<FavoriteList>();
            this.Products = new HashSet<Product>();
            this.Reviews = new HashSet<Review>();
            this.StoreImages = new HashSet<StoreImage>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Rating { get; set; }
        public System.TimeSpan OpenHour { get; set; }
        public System.TimeSpan CloseHour { get; set; }
        public Nullable<decimal> LowestPrice { get; set; }
        public Nullable<decimal> HighestPrice { get; set; }
        public string Description { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteList> FavoriteLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreImage> StoreImages { get; set; }
        public virtual User User { get; set; }
    }
}
