//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public byte Gender { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual FavoriteList FavoriteList { get; set; }
        public virtual Review Review { get; set; }
        public virtual UserImage UserImage { get; set; }
    }
}
